name: oemof_tsam_tutorial_py310
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip= 24.2
  - coincbc
  #- notebook=7.2.2
  - pandas=2.2.0
  - tsam=2.3.6

  - pip:
      - oemof-tabular @ git+https://github.com/oemof/oemof-tabular.git@8c9fcc0b74f63c2ba0d2ad7428dde54bc0d86e06
